### ISSUE TITLE
Retrieving Atomic Tests with specified destination in /opt throws unexpected keyword argument error

### ISSUE THREAD

**Issue by intrusus-dev** [swimlane/atomic-operator#28]
### Expected Behavior
Installation of Atomics into `/opt/atomic` directory so I can start using the tool for testing a NGAV on a linux machine. 
### Actual Behavior
`atomic-operator get_atomics` throws an error when defining the `/opt/atomic` directory as destination.
```
Traceback (most recent call last):
  File "/usr/local/bin/atomic-operator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/atomic_operator/__main__.py", line 6, in main
    fire.Fire({
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/atomic_operator/atomic_operator.py", line 147, in get_atomics
    folder_name = self.download_atomic_red_team_repo(desintation, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/atomic_operator/base.py", line 47, in download_atomic_red_team_repo
    response = requests.get(Base.ATOMIC_RED_TEAM_REPO, stream=True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'destination'
```
### Steps to Reproduce the Problem

1. Disable NGAV or uninstall it if you have installed one to reproduce a clean system state
2. Do a privilege escalation to root with `sudo su -`
2. Install _python3_ with `apt-get install python3`
3. Install _pip_ with `apt-get install python3-pip`
4. Install _atomic-operator_ with `pip install atomic-operator`
5. Create _atomic_ directory in `/opt` with `mkdir /opt/atomic`
6. Install atomics with `atomic-operator get_atomics --destination "/opt/atomic"`
7. Error is getting thrown and atomics won't get installed

### Specifications
**Version:** 0.6.0
**Platform:** Ubuntu 20.04.3 LTS
**Kernel Headers:** linux-headers-5.4.0-90-generic/focal-updates,focal-security,now 5.4.0-90.101 amd64

**Comment by MSAdministrator** [comment]
Thanks for submitting this. I’ll take a look closer this weekend.
