### ISSUE TITLE
No module named 'atomic_operator.execution.base' Error

### ISSUE THREAD

**Issue by fxploit** [swimlane/atomic-operator#55]
**[System information]**
OS : Ubuntu 22.04-x64
python : 3.10.4
python-package :
                             pyyaml==5.4.1
                             fire==0.4.0
                             requests==2.26.0
                             attrs==21.2.0
                             pick==1.2.0

**[Installation commands]**
The first installation attempt was made, but an error occurred.
`pip install atomic-operator`

Installation completed using the command below
```
git clone https://github.com/swimlane/atomic-operator.git
cd atomic-operator
pip install -r requirements.txt
python setup.py install
```

**[Problematic matter]**
It is a normal user and is operated at the time.
However, if you execute with root authority, you will get an error
The cause has not been found and the solution has not been solved.
![image](https://user-images.githubusercontent.com/63603934/174511054-4be704ed-89e3-4a4f-bd57-4f45ff8a83c4.png)

**Comment by HackThePlanetKC** [comment]
Issue exists on MacOS 12.6 on both regular user and sudo. Will try reinstalling.

**Comment by melidosian** [comment]
Hello, I appear to have the same issue on an M1 Mac OS Version 12.6.1. I attempted to follow the instructions [here](https://www.atomic-operator.com/0.8.5/) but came up with issues from the `python setup.py install` command. There where packages I needed to install manually, and I had to run it with `sudo`. Unfortunately, I did not think to save the error logs from that step. I was finally able to successfully complete the installation, but when I run `atomic-operator --help` I see the following error:
`# atomic-operator --help
Traceback (most recent call last):
  File "/usr/local/bin/atomic-operator", line 33, in <module>
    sys.exit(load_entry_point('atomic-operator==0.8.5', 'console_scripts', 'atomic-operator')())
  File "/usr/local/bin/atomic-operator", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.9/site-packages/atomic_operator-0.8.5-py3.9.egg/atomic_operator/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.9/site-packages/atomic_operator-0.8.5-py3.9.egg/atomic_operator/atomic_operator.py", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.9/site-packages/atomic_operator-0.8.5-py3.9.egg/atomic_operator/execution/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/Library/Python/3.9/site-packages/atomic_operator-0.8.5-py3.9.egg/atomic_operator/execution/awsrunner.py", line 3, in <module>
ModuleNotFoundError: No module named 'atomic_operator.execution.base'`

I have tried uninstalling atomic-operator and reinstalling via pip and via the setup.py script without success.

**Comment by MSAdministrator** [comment]
@HackThePlanetKC @fxploit @melidosian @MechiH Hey all - Sorry for the long delay on this but I am looking at this now and this week.

I will need to setup a test environment but can someone verify this is still an issue ?

Also, @fxploit I would not run `atomic-operator ` with `sudo` and would only install it via `-U` or user scope if possible. The elevation of an Atomic Test is determined by the ATomic.yaml file and not any parameters or elevation of atomic-operator itself (but thinking about it, it may be necessary on some hosts). I will take a closer look but further feedback would be helpful!
