### ISSUE TITLE
Error during run all test 

### ISSUE THREAD

**Issue by rajeget** [swimlane/atomic-operator#78]
**Describe the bug**
Error while executing following 

`atomic-operator run --techniques=all
or 
atomic-operator run`

Error as follows :
```
Traceback (most recent call last):
  File "/usr/local/bin/atomic-operator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/atomic_operator/__main__.py", line 6, in main
    fire.Fire({
  File "/home/ubuntu/.local/lib/python3.12/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/atomic_operator/atomic_operator.py", line 355, in run
    self.__run_technique(item)
  File "/home/ubuntu/.local/lib/python3.12/site-packages/atomic_operator/atomic_operator.py", line 106, in __run_technique
    self._set_input_arguments(test, **kwargs)
  File "/home/ubuntu/.local/lib/python3.12/site-packages/atomic_operator/base.py", line 167, in _set_input_arguments
    if k in input.default:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

 
However , single test works fine .

`atomic-operator run --techniques T1564.001 --input_arguments '{"project-id": "some_value", "another_key": "another value"}'`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Ubuntu 24.0 LTS

**Comment by Plensu** [comment]
@rajeget The pypi version seems to have a few issues. I would recommend trying to uninstalling and installing from source.

`pip install git+https://github.com/swimlane/atomic-operator.git#egg=atomic-operator`

**Comment by Benjamin-Connelly** [comment]
Same, not working on 20/22/24.04 LTS Ubuntu for me. I have tried running virtual envs with multiple version of Python.

**Comment by Plensu** [comment]
@Benjamin-Connelly I think the issue is fixed in the source version. You will run into a similar issue where it'll throw an error because of other types not being iterable. I threw together a fix for it and submited a PR for it. 

Feel free to check out my fix and modify the code locally: https://github.com/Plensu/atomic-operator/commit/113a40dc74157d2bc5b999cd6aa75cf58740b368

Or you can install directly from my repo by doing the following:
`pip install git+https://github.com/plensu/atomic-operator.git#egg=atomic-operator`
